export interface CharacterMap {
	[key: string]: string;
}

export const jsxEntitiesMap: CharacterMap = {
	'<': '&lt;',
	'>': '&gt;',
	'&': '&amp;',
	'"': '&quot;',
	"'": '&apos;',
	'¢': '&cent;',
	'£': '&pound;',
	'¥': '&yen;',
	'€': '&euro;',
	'©': '&copy;',
	'®': '&reg;',
	'¤': '&curren;',
	'¦': '&brvbar;',
	'§': '&sect;',
	'¨': '&uml;',
	'°': '&die;',
	'¹': '&sup1;',
	'²': '&sup2;',
	'³': '&sup3;',
	'¼': '&frac14;',
	'½': '&frac12;',
	'¾': '&frac34;',
	'¿': '&iquest;',
	'×': '&times;',
	'÷': '&divide;',
	'ƒ': '&fnof;',
	'†': '&dagger;',
	'‡': '&Dagger;',
	'‰': '&permil;',
	'‹': '&lsaquo;',
	'›': '&rsaquo;',
	'Γ': '&Gamma;',
	'Δ': '&Delta;',
	'Θ': '&Theta;',
	'Ξ': '&Xi;',
	'Π': '&Pi;',
	'Σ': '&Sigma;',
	'Φ': '&Phi;',
	'Ψ': '&Psi;',
	'Ω': '&Omega;',
};
